# DO NOT EDIT: AUTOGENERATED FILE (source: rpc/wikipedia.json)

from iafisher_foundation.prelude import *  # noqa: F401
from lib import kgjson


@dataclass
class CopyEditLLMRequest(kgjson.Base):
    text: str
    model: Optional[str]


@dataclass
class CopyEditLLMResponse(kgjson.Base):
    edited_text: str
    model: str
    conversation_id: int


@dataclass
class CopyEditRegexRequest(kgjson.Base):
    text: str


@dataclass
class CopyEditRegexResponse(kgjson.Base):
    edited_text: str
