# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class Entry:
    entry_id: int
    app: str
    lib: Optional[str]
    machine: str
    event: str
    payload: Dict[str, Any]
    time_created: datetime.datetime

    class T:
        entry_id = sql.Identifier("entry_id")
        entry_id_ = "entry_id"
        app = sql.Identifier("app")
        app_ = "app"
        lib = sql.Identifier("lib")
        lib_ = "lib"
        machine = sql.Identifier("machine")
        machine_ = "machine"
        event = sql.Identifier("event")
        event_ = "event"
        payload = sql.Identifier("payload")
        payload_ = "payload"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"

        table = sql.Identifier("dblog_entries")
        table_ = "dblog_entries"
        star = sql.SQL(", ").join(
            [
                entry_id,
                app,
                lib,
                machine,
                event,
                payload,
                time_created,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                app,
                lib,
                machine,
                event,
                payload,
                time_created,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("app"),
                sql.Placeholder("lib"),
                sql.Placeholder("machine"),
                sql.Placeholder("event"),
                sql.Placeholder("payload"),
                sql.Placeholder("time_created"),
            ]
        )
