# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class Habit:
    name: str
    points: int
    category: str
    once_a_day: bool
    description: str
    deprecated: bool
    time_created: Optional[datetime.datetime]

    class T:
        name = sql.Identifier("name")
        name_ = "name"
        points = sql.Identifier("points")
        points_ = "points"
        category = sql.Identifier("category")
        category_ = "category"
        once_a_day = sql.Identifier("once_a_day")
        once_a_day_ = "once_a_day"
        description = sql.Identifier("description")
        description_ = "description"
        deprecated = sql.Identifier("deprecated")
        deprecated_ = "deprecated"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"

        table = sql.Identifier("habits")
        table_ = "habits"
        star = sql.SQL(", ").join(
            [
                name,
                points,
                category,
                once_a_day,
                description,
                deprecated,
                time_created,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                name,
                points,
                category,
                once_a_day,
                description,
                deprecated,
                time_created,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("name"),
                sql.Placeholder("points"),
                sql.Placeholder("category"),
                sql.Placeholder("once_a_day"),
                sql.Placeholder("description"),
                sql.Placeholder("deprecated"),
                sql.Placeholder("time_created"),
            ]
        )


@dataclass
class HabitEntry:
    date: datetime.date
    habit: str
    original_name: str
    original_points: int
    time_created: Optional[datetime.datetime]

    class T:
        date = sql.Identifier("date")
        date_ = "date"
        habit = sql.Identifier("habit")
        habit_ = "habit"
        original_name = sql.Identifier("original_name")
        original_name_ = "original_name"
        original_points = sql.Identifier("original_points")
        original_points_ = "original_points"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"

        table = sql.Identifier("habit_entries")
        table_ = "habit_entries"
        star = sql.SQL(", ").join(
            [
                date,
                habit,
                original_name,
                original_points,
                time_created,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                date,
                habit,
                original_name,
                original_points,
                time_created,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("date"),
                sql.Placeholder("habit"),
                sql.Placeholder("original_name"),
                sql.Placeholder("original_points"),
                sql.Placeholder("time_created"),
            ]
        )
