// DO NOT EDIT: AUTOGENERATED FILE (source: rpc/wikipedia.json)

export interface CopyEditLLMRequest {
  text: string;
  model: string | null;
}

export interface CopyEditLLMResponse {
  editedText: string;
  model: string;
  conversationId: number;
}

export interface CopyEditRegexRequest {
  text: string;
}

export interface CopyEditRegexResponse {
  editedText: string;
}
