// DO NOT EDIT: AUTOGENERATED FILE (source: rpc/jobs.json)

export interface JobListItem {
  name: string;
  enabled: boolean;
  lastRunTime: string | null;
  nextScheduledTime: string | null;
  lastExitStatus: number | null;
  lastWallTimeSecs: number | null;
}

export interface JobListResponse {
  jobs: JobListItem[];
}

export interface JobRunItem {
  timeRun: string;
  exitStatus: number | null;
  wallTimeSecs: number | null;
  userTimeSecs: number | null;
  systemTimeSecs: number | null;
  maxMemory: number | null;
  logAvailable: boolean;
  logTimestamp: string;
}

export interface JobDetailResponse {
  name: string;
  cmd: string[];
  enabled: boolean;
  schedule: string | null;
  dateAdded: string;
  lastRunTime: string | null;
  nextScheduledTime: string | null;
  lastExitStatus: number | null;
  lastStats: object | null;
  extraPath: string[] | null;
  extraPythonpath: string[] | null;
  workingDirectory: string | null;
  alertHighPriority: boolean;
  runs: JobRunItem[];
}

export interface LogDetailResponse {
  content: string;
}
