# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class EmbeddingDocument:
    document_id: int
    document_name: str
    document_category: str
    time_created: Optional[datetime.datetime]

    class T:
        document_id = sql.Identifier("document_id")
        document_id_ = "document_id"
        document_name = sql.Identifier("document_name")
        document_name_ = "document_name"
        document_category = sql.Identifier("document_category")
        document_category_ = "document_category"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"

        table = sql.Identifier("llm_embedding_documents")
        table_ = "llm_embedding_documents"
        star = sql.SQL(", ").join(
            [
                document_id,
                document_name,
                document_category,
                time_created,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                document_name,
                document_category,
                time_created,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("document_name"),
                sql.Placeholder("document_category"),
                sql.Placeholder("time_created"),
            ]
        )


@dataclass
class EmbeddingChunk:
    chunk_id: int
    document: int
    chunk_title: str
    chunk_content: str
    embedding: Optional[List[float]]

    class T:
        chunk_id = sql.Identifier("chunk_id")
        chunk_id_ = "chunk_id"
        document = sql.Identifier("document")
        document_ = "document"
        chunk_title = sql.Identifier("chunk_title")
        chunk_title_ = "chunk_title"
        chunk_content = sql.Identifier("chunk_content")
        chunk_content_ = "chunk_content"
        embedding = sql.Identifier("embedding")
        embedding_ = "embedding"

        table = sql.Identifier("llm_embedding_chunks")
        table_ = "llm_embedding_chunks"
        star = sql.SQL(", ").join(
            [
                chunk_id,
                document,
                chunk_title,
                chunk_content,
                embedding,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                document,
                chunk_title,
                chunk_content,
                embedding,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("document"),
                sql.Placeholder("chunk_title"),
                sql.Placeholder("chunk_content"),
                sql.Placeholder("embedding"),
            ]
        )
