from iafisher_foundation.prelude import *
from lib import command
from lib.testing import *

from .main import cmd


class Test(Base):
    def test_help_text(self):
        self.assertExpectedInline(
            command.get_help_text_recursive(cmd, program="llm2"),
            """\
Usage: llm2 SUBCMD

Subcommands:

  chat                . Chat with an LLM on the command line.
  code
  code-alone          . An unsupervised, sandboxed coding agent for the monorepo.
  codereview
  conversations       . Manage LLM conversations.
  embeddings          . Work with text embeddings.
  oneshot             . Respond to a prompt and exit.
  proofread
  summarize-titles
  trace               . Trace raw API responses.


------------

Usage: llm2 chat ...

  Chat with an LLM on the command line.

Arguments:

 [-max-tokens ARG]     . (default: 16000)
 [-model ARG]          . (default: 'claude-sonnet-4-6')
 [-reasoning ARG]      . (default: 'medium')
 [-resume ARG]         . (default: None)
 [-temperature ARG]    . (default: 1.0)


------------

Usage: llm2 code ...

Arguments:

 [-auto-approve]
 [-bash]
 [-directory ARG]    . (default: None)
 [-model ARG]        . (default: 'claude-sonnet-4-6')
 [-resume ARG]       . resume a conversation with this ID (default: None)


------------

Usage: llm2 code-alone SUBCMD

  An unsupervised, sandboxed coding agent for the monorepo.

Subcommands:

  accept                . Accept a diff generated by an agent.
  check-for-requests    . Check for enqueued requests and execute the first one.
  prompt                . Prompt the agent.
  test                  . Subcommands for testing.


------------

Usage: llm2 code-alone accept ...

  Accept a diff generated by an agent.

Arguments:

  request_id
  [-code-dir ARG]       . defaults to $KG_CODE_DIR (default: None)
  [-even-if-unclean]    . apply the patch even if `git status` is unclean


------------

Usage: llm2 code-alone check-for-requests ...

  Check for enqueued requests and execute the first one.

Arguments:

 [-code-dir ARG]         . defaults to $KG_CODE_DIR (default: None)
 [-preserve-temp-dir]
 [-verbose]


------------

Usage: llm2 code-alone prompt ...

  Prompt the agent.

Arguments:

  -prompt ARG
  [-model ARG]            . (default: 'claude-sonnet-4-6')
  [-preserve-temp-dir]
  [-verbose]


------------

Usage: llm2 code-alone test SUBCMD

  Subcommands for testing.

Subcommands:

  docker    . Test the Docker container.
  email     . Send a test email.


------------

Usage: llm2 code-alone test email ...

  Send a test email.


------------

Usage: llm2 code-alone test docker ...

  Test the Docker container.

Arguments:

 [-pause]    . pause before cleaning up the container


------------

Usage: llm2 codereview ...

Arguments:

  commit_hash
  [-model ARG]    . (default: 'claude-sonnet-4-6')


------------

Usage: llm2 conversations SUBCMD

  Manage LLM conversations.

Subcommands:

  count-tokens     . Count tokens in a conversation.
  estimate-cost    . Estimate dollar cost of conversation.
  list             . List conversations.
  replay


------------

Usage: llm2 conversations count-tokens ...

  Count tokens in a conversation.

Arguments:

  conversation_id


------------

Usage: llm2 conversations estimate-cost ...

  Estimate dollar cost of conversation.

Arguments:

  conversation_id


------------

Usage: llm2 conversations list ...

  List conversations.


------------

Usage: llm2 conversations replay ...

Arguments:

  conversation_id
  [-raw]
  [-roundtrip]       . round-trip the conversation through the universal message format


------------

Usage: llm2 embeddings SUBCMD

  Work with text embeddings.

Subcommands:

  create    . Create new embeddings.
  search    . Search the embeddings database.


------------

Usage: llm2 embeddings create SUBCMD

  Create new embeddings.

Subcommands:

  obsidian-journal    . Create embeddings from my Obsidian journal files


------------

Usage: llm2 embeddings create obsidian-journal ...

  Create embeddings from my Obsidian journal files

Arguments:

 [-recreate]    . Recreate existing embeddings. (default is to skip them)


------------

Usage: llm2 embeddings search ...

  Search the embeddings database.

Arguments:

  words
  [-limit ARG]    . (default: 5)


------------

Usage: llm2 oneshot ...

  Respond to a prompt and exit.

Arguments:

  words
  [-model ARG]    . (default: 'any_fast')


------------

Usage: llm2 proofread ...

Arguments:

  filepath
  [-model ARG]    . (default: 'any')


------------

Usage: llm2 summarize-titles ...

Arguments:

 [-limit ARG]    . (default: None)


------------

Usage: llm2 trace SUBCMD

  Trace raw API responses.

Subcommands:

  record
  replay


------------

Usage: llm2 trace record ...

Arguments:

  -model ARG
  -outfile ARG
  -prompt ARG
  [-web-search]


------------

Usage: llm2 trace replay ...

Arguments:

  name
""",
        )
