# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class JobRun:
    name: str
    time_run: datetime.datetime
    exit_status: Optional[int]
    wall_time_secs: Optional[float]
    user_time_secs: Optional[float]
    system_time_secs: Optional[float]
    max_memory: Optional[int]

    class T:
        name = sql.Identifier("name")
        name_ = "name"
        time_run = sql.Identifier("time_run")
        time_run_ = "time_run"
        exit_status = sql.Identifier("exit_status")
        exit_status_ = "exit_status"
        wall_time_secs = sql.Identifier("wall_time_secs")
        wall_time_secs_ = "wall_time_secs"
        user_time_secs = sql.Identifier("user_time_secs")
        user_time_secs_ = "user_time_secs"
        system_time_secs = sql.Identifier("system_time_secs")
        system_time_secs_ = "system_time_secs"
        max_memory = sql.Identifier("max_memory")
        max_memory_ = "max_memory"

        table = sql.Identifier("job_runs")
        table_ = "job_runs"
        star = sql.SQL(", ").join(
            [
                name,
                time_run,
                exit_status,
                wall_time_secs,
                user_time_secs,
                system_time_secs,
                max_memory,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                name,
                time_run,
                exit_status,
                wall_time_secs,
                user_time_secs,
                system_time_secs,
                max_memory,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("name"),
                sql.Placeholder("time_run"),
                sql.Placeholder("exit_status"),
                sql.Placeholder("wall_time_secs"),
                sql.Placeholder("user_time_secs"),
                sql.Placeholder("system_time_secs"),
                sql.Placeholder("max_memory"),
            ]
        )
