# DO NOT EDIT: AUTOGENERATED FILE (source: rpc/jobs.json)

from iafisher_foundation.prelude import *  # noqa: F401
from lib import kgjson


@dataclass
class JobListItem(kgjson.Base):
    name: str
    enabled: bool
    last_run_time: Optional[datetime.datetime]
    next_scheduled_time: Optional[datetime.datetime]
    last_exit_status: Optional[int]
    last_wall_time_secs: Optional[float]


@dataclass
class JobListResponse(kgjson.Base):
    jobs: List[JobListItem]


@dataclass
class JobRunItem(kgjson.Base):
    time_run: datetime.datetime
    exit_status: Optional[int]
    wall_time_secs: Optional[float]
    user_time_secs: Optional[float]
    system_time_secs: Optional[float]
    max_memory: Optional[int]
    log_available: bool
    log_timestamp: str


@dataclass
class JobDetailResponse(kgjson.Base):
    name: str
    cmd: List[str]
    enabled: bool
    schedule: Optional[str]
    date_added: datetime.date
    last_run_time: Optional[datetime.datetime]
    next_scheduled_time: Optional[datetime.datetime]
    last_exit_status: Optional[int]
    last_stats: Optional[Dict[str, Any]]
    extra_path: Optional[List[str]]
    extra_pythonpath: Optional[List[str]]
    working_directory: Optional[str]
    alert_high_priority: bool
    runs: List[JobRunItem]


@dataclass
class LogDetailResponse(kgjson.Base):
    content: str
