# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class Bookmark:
    bookmark_id: int
    source_id: str
    title: str
    url: str
    reading_time: str
    appeal: str
    source: str
    reason_archived: str
    tags: List[str]
    time_created: datetime.datetime
    time_archived: Optional[datetime.datetime]

    class T:
        bookmark_id = sql.Identifier("bookmark_id")
        bookmark_id_ = "bookmark_id"
        source_id = sql.Identifier("source_id")
        source_id_ = "source_id"
        title = sql.Identifier("title")
        title_ = "title"
        url = sql.Identifier("url")
        url_ = "url"
        reading_time = sql.Identifier("reading_time")
        reading_time_ = "reading_time"
        appeal = sql.Identifier("appeal")
        appeal_ = "appeal"
        source = sql.Identifier("source")
        source_ = "source"
        reason_archived = sql.Identifier("reason_archived")
        reason_archived_ = "reason_archived"
        tags = sql.Identifier("tags")
        tags_ = "tags"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"
        time_archived = sql.Identifier("time_archived")
        time_archived_ = "time_archived"

        table = sql.Identifier("bookmarks")
        table_ = "bookmarks"
        star = sql.SQL(", ").join(
            [
                bookmark_id,
                source_id,
                title,
                url,
                reading_time,
                appeal,
                source,
                reason_archived,
                tags,
                time_created,
                time_archived,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                source_id,
                title,
                url,
                reading_time,
                appeal,
                source,
                reason_archived,
                tags,
                time_created,
                time_archived,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("source_id"),
                sql.Placeholder("title"),
                sql.Placeholder("url"),
                sql.Placeholder("reading_time"),
                sql.Placeholder("appeal"),
                sql.Placeholder("source"),
                sql.Placeholder("reason_archived"),
                sql.Placeholder("tags"),
                sql.Placeholder("time_created"),
                sql.Placeholder("time_archived"),
            ]
        )
