# DO NOT EDIT: AUTOGENERATED FILE (source: rpc/bookmarks.json)

from iafisher_foundation.prelude import *  # noqa: F401
from lib import kgjson


@dataclass
class Bookmark(kgjson.Base):
    bookmark_id: int
    source_id: str
    title: str
    url: str
    reading_time: str
    appeal: str
    source: str
    reason_archived: str
    tags: List[str]
    no_auto_prune: bool
    time_created: datetime.datetime
    time_archived: Optional[datetime.datetime]


@dataclass
class LoadResponse(kgjson.Base):
    bookmarks: List[Bookmark]


@dataclass
class UpdateRequest(kgjson.Base):
    bookmark_id: int
    title: str
    url: str
    reading_time: str
    appeal: str
    tags: List[str]


@dataclass
class ArchiveRequest(kgjson.Base):
    bookmark_id: int
    reason: str


@dataclass
class UnarchiveRequest(kgjson.Base):
    bookmark_id: int


@dataclass
class MarkNoAutoPruneRequest(kgjson.Base):
    bookmark_id: int
