from typing import Annotated

from iafisher_foundation.prelude import *
from lib import command, kgenv, kgjson


@dataclass
class RpcTypeField(kgjson.Base):
    name: str
    type: str

    def to_python_code(self, known_types: Set[str]) -> str:
        type_name = type_name_to_python(self.type, known_types)
        return f"{self.name}: {type_name}"

    def to_typescript_code(self, known_types: Set[str]) -> str:
        type_name = type_name_to_typescript(self.type, known_types)
        return f"{kgjson.snake_to_camel(self.name)}: {type_name}"


def type_name_to_python(type_name: str, known_types: Set[str]) -> str:
    if type_name.endswith("[]"):
        inner_type = type_name_to_python(type_name[:-2], known_types)
        return f"List[{inner_type}]"
    elif type_name.endswith("?"):
        inner_type = type_name_to_python(type_name[:-1], known_types)
        return f"Optional[{inner_type}]"
    elif type_name == "string":
        return "str"
    elif type_name == "int":
        return "int"
    elif type_name == "float":
        return "float"
    elif type_name == "date":
        return "datetime.date"
    elif type_name == "datetime":
        return "datetime.datetime"
    elif type_name == "boolean":
        return "bool"
    elif type_name == "dict":
        return "Dict[str, Any]"
    elif type_name == "any":
        return "Any"
    elif type_name in known_types:
        return type_name
    else:
        raise KgError("unknown type name", type_name=type_name, known_types=known_types)


def type_name_to_typescript(type_name: str, known_types: Set[str]) -> str:
    if type_name.endswith("[]"):
        inner_type = type_name_to_typescript(type_name[:-2], known_types)
        return f"{inner_type}[]"
    elif type_name.endswith("?"):
        inner_type = type_name_to_typescript(type_name[:-1], known_types)
        return f"{inner_type} | null"
    elif type_name == "string":
        return "string"
    elif type_name == "int" or type_name == "float":
        return "number"
    elif type_name == "date":
        return "string"
    elif type_name == "datetime":
        return "string"
    elif type_name == "boolean":
        return "boolean"
    elif type_name == "dict":
        return "object"
    elif type_name == "any":
        return "any"
    elif type_name in known_types:
        return type_name
    else:
        raise KgError("unknown type name", type_name=type_name, known_types=known_types)


@dataclass
class RpcType(kgjson.Base):
    name: str
    fields: List[RpcTypeField]

    def to_python_code(self, known_types: Set[str]) -> str:
        if len(self.fields) > 0:
            fields = "\n".join(
                f"    {field.to_python_code(known_types)}" for field in self.fields
            )
        else:
            fields = "    pass"
        return f"@dataclass\nclass {self.name}(kgjson.Base):\n{fields}\n"

    def to_typescript_code(self, known_types: Set[str]) -> str:
        if len(self.fields) > 0:
            fields = (
                "\n"
                + (
                    "\n".join(
                        f"  {field.to_typescript_code(known_types)};"
                        for field in self.fields
                    )
                )
                + "\n"
            )
        else:
            fields = ""
        return "export interface %(name)s {%(fields)s}\n" % dict(
            name=self.name, fields=fields
        )


_do_not_edit = "DO NOT EDIT: AUTOGENERATED FILE"


@dataclass
class RpcSchema(kgjson.Base):
    types: List[RpcType]
    python_file: str
    typescript_file: str

    def to_python_code(self, source_path: pathlib.Path) -> str:
        known_types = self._known_types()

        builder: List[str] = []
        builder.append(
            f"# {_do_not_edit} (source: {source_path})\n\n"
            "from iafisher_foundation.prelude import *  # noqa: F401\n"
            "from lib import kgjson\n\n\n"
        )
        for type_ in self.types:
            builder.append(type_.to_python_code(known_types))
            builder.append("\n\n")
        return "".join(builder).rstrip() + "\n"

    def to_typescript_code(self, source_path: pathlib.Path) -> str:
        known_types = self._known_types()

        builder: List[str] = []
        builder.append(f"// {_do_not_edit} (source: {source_path})\n\n")
        for type_ in self.types:
            builder.append(type_.to_typescript_code(known_types))
            builder.append("\n")
        return "".join(builder).rstrip() + "\n"

    def _known_types(self) -> Set[str]:
        return set(type_.name for type_ in self.types)


def main(
    *,
    check: Annotated[
        bool,
        command.Extra(
            help="check if any files would be updated, without actually updating them"
        ),
    ],
) -> None:
    os.chdir(kgenv.get_code_dir())
    rpc_folder = pathlib.Path("rpc")
    would_write = False
    for json_file in rpc_folder.glob("*.json"):
        schema = RpcSchema.load(json_file)
        python_code = schema.to_python_code(json_file)
        typescript_code = schema.to_typescript_code(json_file)

        existing_python_code = read_file(schema.python_file)
        existing_typescript_code = read_file(schema.typescript_file)

        if existing_python_code != python_code:
            would_write = True
            print(schema.python_file)
            if not check:
                pathlib.Path(schema.python_file).write_text(python_code)

        if existing_typescript_code != typescript_code:
            would_write = True
            print(schema.typescript_file)
            if not check:
                pathlib.Path(schema.typescript_file).write_text(typescript_code)

    if check and would_write:
        sys.exit(1)


def read_file(p: PathLike) -> str:
    try:
        return pathlib.Path(p).read_text()
    except FileNotFoundError:
        return ""


cmd = command.Command.from_function(main)

if __name__ == "__main__":
    command.dispatch(cmd)
