// DO NOT EDIT: AUTOGENERATED FILE (source: rpc/llmweb.json)

export interface Message {
  messageId: number;
  role: string;
  content: string;
  vote: string;
  timeCreated: string;
}

export interface ConversationResponse {
  model: string;
  messages: Message[];
  tokenCount: number;
  llmConversationId: number;
}

export interface StartRequest {
  model: string | null;
}

export interface StartResponse {
  conversationId: number;
}

export interface VoteRequest {
  messageId: number;
  vote: string;
}

export interface VoteResponse {}

export interface PromptRequest {
  conversationId: number;
  message: string;
}

export interface FetchConversationsResponseItem {
  conversationId: number;
  title: string;
  model: string;
  timeCreated: string;
  messageCount: number;
}

export interface FetchConversationsResponse {
  conversations: FetchConversationsResponseItem[];
}

export interface TranscriptResponse {
  raw: any[];
  universal: any[];
}
