// DO NOT EDIT: AUTOGENERATED FILE (source: rpc/bookmarks.json)

export interface Bookmark {
  bookmarkId: number;
  sourceId: string;
  title: string;
  url: string;
  readingTime: string;
  appeal: string;
  source: string;
  reasonArchived: string;
  tags: string[];
  timeCreated: string;
  timeArchived: string | null;
}

export interface LoadResponse {
  bookmarks: Bookmark[];
}

export interface UpdateRequest {
  bookmarkId: number;
  title: string;
  url: string;
  readingTime: string;
  appeal: string;
  tags: string[];
}

export interface ArchiveRequest {
  bookmarkId: number;
  reason: string;
}

export interface UnarchiveRequest {
  bookmarkId: number;
}
