# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class Conversation:
    conversation_id: int
    llm_conversation_id: Optional[int]
    title: str
    time_created: datetime.datetime

    class T:
        conversation_id = sql.Identifier("conversation_id")
        conversation_id_ = "conversation_id"
        llm_conversation_id = sql.Identifier("llm_conversation_id")
        llm_conversation_id_ = "llm_conversation_id"
        title = sql.Identifier("title")
        title_ = "title"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"

        table = sql.Identifier("llmweb_conversations")
        table_ = "llmweb_conversations"
        star = sql.SQL(", ").join(
            [
                conversation_id,
                llm_conversation_id,
                title,
                time_created,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                llm_conversation_id,
                title,
                time_created,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("llm_conversation_id"),
                sql.Placeholder("title"),
                sql.Placeholder("time_created"),
            ]
        )


@dataclass
class Message:
    message_id: int
    conversation_id: Optional[int]
    role: str
    content: str
    vote: str
    time_created: datetime.datetime

    class T:
        message_id = sql.Identifier("message_id")
        message_id_ = "message_id"
        conversation_id = sql.Identifier("conversation_id")
        conversation_id_ = "conversation_id"
        role = sql.Identifier("role")
        role_ = "role"
        content = sql.Identifier("content")
        content_ = "content"
        vote = sql.Identifier("vote")
        vote_ = "vote"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"

        table = sql.Identifier("llmweb_messages")
        table_ = "llmweb_messages"
        star = sql.SQL(", ").join(
            [
                message_id,
                conversation_id,
                role,
                content,
                vote,
                time_created,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                conversation_id,
                role,
                content,
                vote,
                time_created,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("conversation_id"),
                sql.Placeholder("role"),
                sql.Placeholder("content"),
                sql.Placeholder("vote"),
                sql.Placeholder("time_created"),
            ]
        )
