# DO NOT EDIT: AUTOGENERATED FILE (source: rpc/llmweb.json)

from iafisher_foundation.prelude import *  # noqa: F401
from lib import kgjson


@dataclass
class Message(kgjson.Base):
    message_id: int
    role: str
    content: str
    vote: str
    time_created: datetime.datetime


@dataclass
class ConversationResponse(kgjson.Base):
    model: str
    messages: List[Message]
    token_count: int
    llm_conversation_id: int


@dataclass
class StartRequest(kgjson.Base):
    model: Optional[str]


@dataclass
class StartResponse(kgjson.Base):
    conversation_id: int


@dataclass
class VoteRequest(kgjson.Base):
    message_id: int
    vote: str


@dataclass
class VoteResponse(kgjson.Base):
    pass


@dataclass
class PromptRequest(kgjson.Base):
    conversation_id: int
    message: str


@dataclass
class FetchConversationsResponseItem(kgjson.Base):
    conversation_id: int
    title: str
    model: str
    time_created: datetime.datetime
    message_count: int


@dataclass
class FetchConversationsResponse(kgjson.Base):
    conversations: List[FetchConversationsResponseItem]


@dataclass
class TranscriptResponse(kgjson.Base):
    raw: List[Any]
    universal: List[Any]
