# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class Book:
    title: str
    author: str
    date_started: datetime.date
    date_finished: Optional[datetime.date]
    pages: Optional[int]

    class T:
        title = sql.Identifier("title")
        title_ = "title"
        author = sql.Identifier("author")
        author_ = "author"
        date_started = sql.Identifier("date_started")
        date_started_ = "date_started"
        date_finished = sql.Identifier("date_finished")
        date_finished_ = "date_finished"
        pages = sql.Identifier("pages")
        pages_ = "pages"

        table = sql.Identifier("books")
        table_ = "books"
        star = sql.SQL(", ").join(
            [
                title,
                author,
                date_started,
                date_finished,
                pages,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                title,
                author,
                date_started,
                date_finished,
                pages,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("title"),
                sql.Placeholder("author"),
                sql.Placeholder("date_started"),
                sql.Placeholder("date_finished"),
                sql.Placeholder("pages"),
            ]
        )
