import os
import sys
import typing

from app.iafisher.common import DO_NOT_PUBLISH_PROPERTY
from iafisher_foundation.prelude import *
from lib import command, githelper, obsidian


def main(*, dry_run: bool) -> None:
    os.chdir(obsidian.Vault.personal_site().path())
    if dry_run:
        write_stats(sys.stdout)
    else:
        with open("stats.md", "w") as f:
            write_stats(f)


def write_stats(out: typing.IO[str]) -> None:
    def w(*args: Any, **kwargs: Any) -> None:
        print(*args, file=out, **kwargs)

    file_count = 0
    wiki_file_count = 0
    note_file_count = 0
    byte_count = 0
    word_count = 0
    lines_of_code_count = 0
    vault = obsidian.Vault.personal_site()
    for path in vault.markdown_files():
        document = obsidian.Document.from_path(path)
        properties = document.properties()
        if DO_NOT_PUBLISH_PROPERTY in properties:
            continue

        relpath = path.relative_to(vault.path())
        file_count += 1
        if relpath.parts[0] == "wiki":
            wiki_file_count += 1

        if relpath.parts[0] == "notes":
            note_file_count += 1

        byte_count += os.stat(path).st_size
        word_count += document.word_count()
        lines_of_code_count += document.lines_of_code_count()

    last_commit_time = githelper.last_commit_time()
    w("---")
    w("iafisher-hide-sidebar: true")
    w("---\n")
    w("# Site stats")
    w("<!-- ATTENTION: This file is auto-generated by script. -->\n")
    w(f"- Last updated: **{last_commit_time.date()}**")
    kb = byte_count / 1000
    w(f"- **{file_count}** files, totaling **{kb:,.1f}** KB")
    w(f"    - **{wiki_file_count}** wiki files")
    w(f"    - **{note_file_count}** note files")
    w(f"- **{word_count:,}** words and **{lines_of_code_count:,}** lines of code")


cmd = command.Command.from_function(main, help="Update the site stats page.")
