# DO NOT EDIT: AUTOGENERATED FILE
from iafisher_foundation.prelude import *

from psycopg import sql


@dataclass
class Golink:
    name: Optional[str]
    url: str
    visit_count: int
    is_deprecated: bool
    time_created: datetime.datetime
    time_last_updated: datetime.datetime
    time_last_visited: Optional[datetime.datetime]

    class T:
        name = sql.Identifier("name")
        name_ = "name"
        url = sql.Identifier("url")
        url_ = "url"
        visit_count = sql.Identifier("visit_count")
        visit_count_ = "visit_count"
        is_deprecated = sql.Identifier("is_deprecated")
        is_deprecated_ = "is_deprecated"
        time_created = sql.Identifier("time_created")
        time_created_ = "time_created"
        time_last_updated = sql.Identifier("time_last_updated")
        time_last_updated_ = "time_last_updated"
        time_last_visited = sql.Identifier("time_last_visited")
        time_last_visited_ = "time_last_visited"

        table = sql.Identifier("golinks")
        table_ = "golinks"
        star = sql.SQL(", ").join(
            [
                name,
                url,
                visit_count,
                is_deprecated,
                time_created,
                time_last_updated,
                time_last_visited,
            ]
        )
        star_for_insert = sql.SQL(", ").join(
            [
                name,
                url,
                visit_count,
                is_deprecated,
                time_created,
                time_last_updated,
                time_last_visited,
            ]
        )
        placeholders = sql.SQL(", ").join(
            [
                sql.Placeholder("name"),
                sql.Placeholder("url"),
                sql.Placeholder("visit_count"),
                sql.Placeholder("is_deprecated"),
                sql.Placeholder("time_created"),
                sql.Placeholder("time_last_updated"),
                sql.Placeholder("time_last_visited"),
            ]
        )
